import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { isContextFresh } from '../pipeline.js';
import { computeSignatureHash } from '@contextforge/generator';

function makeTmp(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'cf-pipeline-test-'));
}

function writeContextMd(dir: string, hash: string): void {
  fs.writeFileSync(
    path.join(dir, '.context.md'),
    `# Project Context\n\n> Generated by ContextForge\n> Last updated: 2024-01-01T00:00:00.000Z\n> Signature hash: ${hash}\n\n`,
  );
}

describe('isContextFresh', () => {
  let tmpDir: string;

  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => { fs.rmSync(tmpDir, { recursive: true, force: true }); });

  it('returns false when .context.md does not exist', () => {
    expect(isContextFresh(tmpDir)).toBe(false);
  });

  it('returns false when .context.md has no signature hash line', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), '# Project Context\n\nNo hash here.\n');
    expect(isContextFresh(tmpDir)).toBe(false);
  });

  it('returns false when stored hash does not match current codebase', () => {
    writeContextMd(tmpDir, '000000de');
    expect(isContextFresh(tmpDir)).toBe(false);
  });

  it('returns true when stored hash matches current codebase', () => {
    const correctHash = computeSignatureHash(tmpDir);
    writeContextMd(tmpDir, correctHash);
    expect(isContextFresh(tmpDir)).toBe(true);
  });

  it('returns false after package.json is added (hash changes)', () => {
    const correctHash = computeSignatureHash(tmpDir);
    writeContextMd(tmpDir, correctHash);
    expect(isContextFresh(tmpDir)).toBe(true);

    // Mutate the signature
    fs.writeFileSync(path.join(tmpDir, 'package.json'), '{"name":"test"}');
    expect(isContextFresh(tmpDir)).toBe(false);
  });
});
