import * as fs from 'node:fs';
import * as path from 'node:path';
import type { GeneratorInput, SectionName } from './types.js';
import { renderAllSections } from './renderer.js';
import { patchContextFile } from './patcher.js';
import { computeSignatureHash } from './hash.js';
import { IDEFileWriter } from './ide-writer.js';

export class ContextFileGenerator {
  constructor(private readonly input: GeneratorInput) {}

  async generate(): Promise<void> {
    const contextPath = path.join(this.input.projectRoot, '.context.md');
    const existing = this.readExisting(contextPath);
    const sections = renderAllSections(this.input);

    // Build delimited section blocks
    const sectionBlocks = new Map<string, string>();
    for (const [name, { content, inputHash }] of sections) {
      sectionBlocks.set(name, wrapSection(name, inputHash, content));
    }

    const patched = patchContextFile(existing, sectionBlocks as Map<SectionName, string>);
    const withHeader = updateHeader(patched, this.input.projectRoot);

    fs.writeFileSync(contextPath, withHeader, 'utf8');

    // Write IDE-specific file if IDE detected
    const ideWriter = new IDEFileWriter(this.input.projectRoot);
    const ide = ideWriter.detectIde();
    if (ide) {
      const ideContent = ideWriter.formatForIde(ide, withHeader);
      ideWriter.write(ide, ideContent);
    }
  }

  private readExisting(contextPath: string): string {
    try {
      return fs.readFileSync(contextPath, 'utf8');
    } catch {
      return '';
    }
  }
}

export function wrapSection(name: string, inputHash: string, content: string): string {
  return `<!-- contextforge:${name}:start hash="${inputHash}" -->\n${content}\n<!-- contextforge:${name}:end -->`;
}

function updateHeader(content: string, projectRoot: string): string {
  const sigHash = computeSignatureHash(projectRoot);
  const timestamp = new Date().toISOString();
  const header = `# Project Context\n\n> Generated by ContextForge\n> Last updated: ${timestamp}\n> Signature hash: ${sigHash}\n\n`;

  // Replace existing header or prepend
  const firstSection = content.indexOf('<!-- contextforge:');
  if (firstSection === -1) {
    return header + content;
  }
  // If content starts with a header (starts with '#'), skip it and go straight to first section
  return header + content.slice(content.startsWith('# ') ? firstSection : 0);
}
