import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { runAudit } from '../commands/audit.js';
import {
  checkContextExists,
  checkContextFresh,
  checkIdFilePresent,
  checkSectionsComplete,
  checkNoContestedConventions,
  checkTemplatesApplied,
  runAllChecks,
} from '../audit/checks.js';

function makeTmp(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'cf-audit-test-'));
}

// Minimal .context.md with all 6 sections and a stale hash
function makeContextMd(sections: string[] = ['stack', 'structure', 'conventions', 'dependencies', 'anti-patterns', 'decisions']): string {
  const header = '# Project Context\n\n> Generated by ContextForge\n> Last updated: 2024-01-01T00:00:00.000Z\n> Signature hash: 000000deadbeef\n\n';
  const body = sections.map(name =>
    `<!-- contextforge:${name}:start hash="abc" -->\n## ${name}\ncontent\n<!-- contextforge:${name}:end -->`,
  ).join('\n\n');
  return header + body;
}

describe('checkContextExists', () => {
  let tmpDir: string;
  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => { fs.rmSync(tmpDir, { recursive: true, force: true }); });

  it('fails when .context.md is missing', () => {
    const check = checkContextExists(tmpDir);
    expect(check.status).toBe('fail');
    expect(check.fixable).toBe(true);
  });

  it('passes when .context.md exists', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), '# Project Context\n');
    const check = checkContextExists(tmpDir);
    expect(check.status).toBe('pass');
  });
});

describe('checkContextFresh', () => {
  let tmpDir: string;
  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => { fs.rmSync(tmpDir, { recursive: true, force: true }); });

  it('fails when .context.md is missing', () => {
    const check = checkContextFresh(tmpDir);
    expect(check.status).toBe('fail');
  });

  it('warns when signature hash is stale', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), makeContextMd());
    const check = checkContextFresh(tmpDir);
    expect(check.status).toBe('warn');
    expect(check.fixable).toBe(true);
    expect(check.detail).toContain('stale');
  });
});

describe('checkIdFilePresent', () => {
  let tmpDir: string;
  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => {
    delete process.env.CONTEXTFORGE_IDE;
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('warns when no IDE is detected', () => {
    delete process.env.CONTEXTFORGE_IDE;
    const check = checkIdFilePresent(tmpDir);
    expect(check.status).toBe('warn');
    expect(check.fixable).toBe(false);
  });

  it('warns when IDE is detected but file is missing', () => {
    process.env.CONTEXTFORGE_IDE = 'claude-code';
    const check = checkIdFilePresent(tmpDir);
    expect(check.status).toBe('warn');
    expect(check.fixable).toBe(true);
    expect(check.detail).toContain('CLAUDE.md');
  });

  it('passes when IDE file exists', () => {
    process.env.CONTEXTFORGE_IDE = 'claude-code';
    fs.writeFileSync(path.join(tmpDir, 'CLAUDE.md'), '# Context\n');
    const check = checkIdFilePresent(tmpDir);
    expect(check.status).toBe('pass');
  });
});

describe('checkSectionsComplete', () => {
  let tmpDir: string;
  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => { fs.rmSync(tmpDir, { recursive: true, force: true }); });

  it('fails when .context.md is missing', () => {
    const check = checkSectionsComplete(tmpDir);
    expect(check.status).toBe('fail');
  });

  it('passes when all 6 sections are present', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), makeContextMd());
    const check = checkSectionsComplete(tmpDir);
    expect(check.status).toBe('pass');
    expect(check.detail).toContain('6');
  });

  it('warns when sections are missing', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), makeContextMd(['stack', 'structure']));
    const check = checkSectionsComplete(tmpDir);
    expect(check.status).toBe('warn');
    expect(check.detail).toContain('Missing sections');
    expect(check.detail).toContain('conventions');
  });
});

describe('checkNoContestedConventions', () => {
  let tmpDir: string;
  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => { fs.rmSync(tmpDir, { recursive: true, force: true }); });

  it('fails when .context.md is missing', () => {
    const check = checkNoContestedConventions(tmpDir);
    expect(check.status).toBe('fail');
  });

  it('passes when no ⚠ Contested markers present', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), makeContextMd());
    const check = checkNoContestedConventions(tmpDir);
    expect(check.status).toBe('pass');
  });

  it('warns when contested conventions are present', () => {
    const content = makeContextMd() + '\n\n⚠ Contested: camelCase vs snake_case (60% vs 40%)\n⚠ Contested: import style';
    fs.writeFileSync(path.join(tmpDir, '.context.md'), content);
    const check = checkNoContestedConventions(tmpDir);
    expect(check.status).toBe('warn');
    expect(check.fixable).toBe(false);
    expect(check.detail).toContain('2');
  });
});

describe('checkTemplatesApplied', () => {
  let tmpDir: string;
  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => {
    delete process.env.CONTEXTFORGE_IDE;
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('warns when no IDE detected', () => {
    delete process.env.CONTEXTFORGE_IDE;
    const check = checkTemplatesApplied(tmpDir);
    expect(check.status).toBe('warn');
  });

  it('warns when template dir is empty', () => {
    process.env.CONTEXTFORGE_IDE = 'claude-code';
    const check = checkTemplatesApplied(tmpDir);
    expect(check.status).toBe('warn');
    expect(check.fixable).toBe(true);
    expect(check.detail).toContain('.claude/commands');
  });

  it('passes when at least one template file exists', () => {
    process.env.CONTEXTFORGE_IDE = 'claude-code';
    const dir = path.join(tmpDir, '.claude', 'commands');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'feature.md'), '# Feature\n');
    const check = checkTemplatesApplied(tmpDir);
    expect(check.status).toBe('pass');
  });
});

describe('runAllChecks', () => {
  let tmpDir: string;
  beforeEach(() => { tmpDir = makeTmp(); });
  afterEach(() => {
    delete process.env.CONTEXTFORGE_IDE;
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('returns 6 checks', () => {
    const checks = runAllChecks(tmpDir);
    expect(checks).toHaveLength(6);
  });

  it('check IDs are all unique', () => {
    const checks = runAllChecks(tmpDir);
    const ids = checks.map(c => c.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('all checks fail/warn for an empty dir', () => {
    delete process.env.CONTEXTFORGE_IDE;
    const checks = runAllChecks(tmpDir);
    const passing = checks.filter(c => c.status === 'pass');
    expect(passing).toHaveLength(0);
  });
});

describe('runAudit --json', () => {
  let tmpDir: string;
  let stdout: string[];

  beforeEach(() => {
    tmpDir = makeTmp();
    stdout = [];
    vi.spyOn(console, 'log').mockImplementation((msg: string) => { stdout.push(msg); });
    vi.spyOn(process, 'exit').mockImplementation((() => {}) as () => never);
  });

  afterEach(() => {
    delete process.env.CONTEXTFORGE_IDE;
    vi.restoreAllMocks();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('outputs valid JSON with expected shape', async () => {
    await runAudit({ root: tmpDir, json: true });
    const output = stdout.join('');
    const report = JSON.parse(output);
    expect(report).toHaveProperty('projectRoot');
    expect(report).toHaveProperty('timestamp');
    expect(report).toHaveProperty('checks');
    expect(report).toHaveProperty('passed');
    expect(report).toHaveProperty('warned');
    expect(report).toHaveProperty('failed');
    expect(Array.isArray(report.checks)).toBe(true);
  });

  it('JSON checks array has 6 entries', async () => {
    await runAudit({ root: tmpDir, json: true });
    const report = JSON.parse(stdout.join(''));
    expect(report.checks).toHaveLength(6);
  });

  it('each check in JSON has id, status, detail, fixable', async () => {
    await runAudit({ root: tmpDir, json: true });
    const report = JSON.parse(stdout.join(''));
    for (const check of report.checks) {
      expect(check).toHaveProperty('id');
      expect(check).toHaveProperty('status');
      expect(check).toHaveProperty('detail');
      expect(check).toHaveProperty('fixable');
      expect(['pass', 'warn', 'fail']).toContain(check.status);
    }
  });

  it('failed count equals number of fail-status checks', async () => {
    await runAudit({ root: tmpDir, json: true });
    const report = JSON.parse(stdout.join(''));
    const failCount = report.checks.filter((c: { status: string }) => c.status === 'fail').length;
    expect(report.failed).toBe(failCount);
  });
});
