import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { runStatus } from '../commands/status.js';
import { runSwitch } from '../commands/switch.js';
import { runTemplatesList, BUILTIN_TEMPLATES } from '../commands/templates.js';

function makeTmp(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'cf-cli-test-'));
}

// Minimal .context.md with a stale signature hash
const STALE_CONTEXT = `# Project Context

> Generated by ContextForge
> Last updated: 2024-01-01T00:00:00.000Z
> Signature hash: 000000deadbeef

`;

describe('runStatus', () => {
  let tmpDir: string;
  let stdout: string[];

  beforeEach(() => {
    tmpDir = makeTmp();
    stdout = [];
    vi.spyOn(console, 'log').mockImplementation((msg: string) => { stdout.push(msg); });
  });

  afterEach(() => {
    vi.restoreAllMocks();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('reports not initialized when .context.md is missing', () => {
    runStatus({ root: tmpDir });
    expect(stdout.join('\n')).toContain('not initialized');
  });

  it('suggests init when not initialized', () => {
    runStatus({ root: tmpDir });
    expect(stdout.join('\n')).toContain('contextforge init');
  });

  it('reports stale when signature hash does not match', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), STALE_CONTEXT);
    runStatus({ root: tmpDir });
    expect(stdout.join('\n')).toContain('stale');
  });

  it('shows last updated date from header', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), STALE_CONTEXT);
    runStatus({ root: tmpDir });
    expect(stdout.join('\n')).toContain('2024-01-01');
  });

  it('shows sig hash from header', () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), STALE_CONTEXT);
    runStatus({ root: tmpDir });
    expect(stdout.join('\n')).toContain('000000deadbeef');
  });
});

describe('runSwitch', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmp();
  });

  afterEach(() => {
    vi.restoreAllMocks();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('exits 1 when .context.md is missing', async () => {
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation((() => {}) as () => never);
    vi.spyOn(console, 'error').mockImplementation(() => {});
    await runSwitch('cursor', { root: tmpDir });
    expect(exitSpy).toHaveBeenCalledWith(1);
  });

  it('writes .cursorrules when switching to cursor', async () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), '# Project Context\n\nSome content.\n');
    vi.spyOn(console, 'log').mockImplementation(() => {});
    await runSwitch('cursor', { root: tmpDir });
    expect(fs.existsSync(path.join(tmpDir, '.cursorrules'))).toBe(true);
  });

  it('writes CLAUDE.md when switching to claude-code', async () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), '# Project Context\n\nSome content.\n');
    vi.spyOn(console, 'log').mockImplementation(() => {});
    await runSwitch('claude-code', { root: tmpDir });
    expect(fs.existsSync(path.join(tmpDir, 'CLAUDE.md'))).toBe(true);
  });

  it('writes .windsurfrules when switching to windsurf', async () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), '# Project Context\n\nSome content.\n');
    vi.spyOn(console, 'log').mockImplementation(() => {});
    await runSwitch('windsurf', { root: tmpDir });
    expect(fs.existsSync(path.join(tmpDir, '.windsurfrules'))).toBe(true);
  });

  it('writes copilot-instructions.md when switching to vscode', async () => {
    fs.writeFileSync(path.join(tmpDir, '.context.md'), '# Project Context\n\nSome content.\n');
    vi.spyOn(console, 'log').mockImplementation(() => {});
    await runSwitch('vscode', { root: tmpDir });
    expect(fs.existsSync(path.join(tmpDir, '.github', 'copilot-instructions.md'))).toBe(true);
  });

  it('preserves content when switching IDEs', async () => {
    const content = '# Project Context\n\nMy important content.\n';
    fs.writeFileSync(path.join(tmpDir, '.context.md'), content);
    vi.spyOn(console, 'log').mockImplementation(() => {});
    await runSwitch('cursor', { root: tmpDir });
    const written = fs.readFileSync(path.join(tmpDir, '.cursorrules'), 'utf8');
    expect(written).toContain('My important content.');
  });

  it('strips contextforge delimiters when writing IDE file', async () => {
    const content = '<!-- contextforge:stack:start hash="abc" -->\n## Stack\nNode.js\n<!-- contextforge:stack:end -->\n';
    fs.writeFileSync(path.join(tmpDir, '.context.md'), content);
    vi.spyOn(console, 'log').mockImplementation(() => {});
    await runSwitch('cursor', { root: tmpDir });
    const written = fs.readFileSync(path.join(tmpDir, '.cursorrules'), 'utf8');
    expect(written).not.toContain('contextforge:stack:start');
    expect(written).toContain('## Stack');
  });
});

describe('runTemplatesList', () => {
  afterEach(() => vi.restoreAllMocks());

  it('prints all builtin template names', () => {
    const lines: string[] = [];
    vi.spyOn(console, 'log').mockImplementation((msg: string) => { lines.push(msg); });
    runTemplatesList();
    const output = lines.join('\n');
    for (const t of BUILTIN_TEMPLATES) {
      expect(output).toContain(t.name);
    }
  });

  it('prints template descriptions', () => {
    const lines: string[] = [];
    vi.spyOn(console, 'log').mockImplementation((msg: string) => { lines.push(msg); });
    runTemplatesList();
    const output = lines.join('\n');
    expect(output).toContain('feature');
    expect(output).toContain('bugfix');
    expect(output).toContain('refactor');
  });
});
